### ISSUE TITLE
Update templates with multiple payloads / request with flow to avoid unnecessary requests

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#11244]
### Template IDs or paths

Here is list of top templates with multiple request using payloads or request list that can reviewed further to add flow rule for tech detection before running actual checks.

```[tasklist]
### Tasks
- [x] http/cves/2014/CVE-2014-2383.yaml
- [x] http/cves/2017/CVE-2017-17562.yaml
- [x] http/cves/2019/CVE-2019-17382.yaml
- [x] http/cves/2021/CVE-2021-26084.yaml
- [x] http/cves/2022/CVE-2022-2034.yaml
- [x] http/cves/2023/CVE-2023-24489.yaml
- [x] http/cves/2023/CVE-2023-27524.yaml
- [x] http/cves/2023/CVE-2023-2825.yaml
- [ ] http/cves/2023/CVE-2023-46214.yaml
- [x] http/cves/2023/CVE-2023-6379.yaml
- [x] http/default-logins/apache/tomcat-default-login.yaml
- [x] http/default-logins/couchdb/couchdb-default-login.yaml
- [x] http/default-logins/esafenet-cdg-default-login.yaml
- [x] http/default-logins/goip-default-login.yaml
- [x] http/default-logins/jboss/jboss-jbpm-default-login.yaml
- [x] http/default-logins/jboss/jmx-default-login.yaml
- [x] http/default-logins/oracle/peoplesoft-default-login.yaml
- [x] http/default-logins/phpmyadmin/phpmyadmin-default-login.yaml
- [x] http/default-logins/weblogic/weblogic-weak-login.yaml
- [ ] http/exposed-panels/adminer-panel-detect.yaml
- [ ] http/exposed-panels/compalex-panel-detect.yaml
- [ ] http/exposed-panels/openam-panel.yaml
- [ ] http/exposed-panels/oracle-peoplesoft-panel.yaml
- [ ] http/exposed-panels/phpmyadmin-panel.yaml
- [ ] http/exposed-panels/webeditors-check-detect.yaml
- [x] http/exposures/apis/swagger-api.yaml
- [ ] http/exposures/backups/php-backup-files.yaml
- [ ] http/exposures/backups/sql-dump.yaml
- [ ] http/exposures/backups/sql-server-dump.yaml
- [ ] http/exposures/backups/zip-backup-files.yaml
- [ ] http/exposures/configs/codeigniter-env.yaml
- [ ] http/exposures/configs/deployment-ini.yaml
- [ ] http/exposures/configs/phpinfo-files.yaml
- [ ] http/exposures/configs/server-private-keys.yaml
- [ ] http/exposures/configs/zend-config-file.yaml
- [ ] http/exposures/files/routes-ini.yaml
- [ ] http/exposures/files/shellscripts.yaml
- [ ] http/exposures/logs/error-logs.yaml
- [ ] http/exposures/logs/roundcube-log-disclosure.yaml
- [ ] http/fuzzing/cache-poisoning-fuzz.yaml
- [ ] http/fuzzing/header-command-injection.yaml
- [ ] http/fuzzing/linux-lfi-fuzzing.yaml
- [ ] http/fuzzing/mdb-database-file.yaml
- [ ] http/fuzzing/prestashop-module-fuzz.yaml
- [ ] http/fuzzing/waf-fuzz.yaml
- [x] http/fuzzing/wordpress-plugins-detect.yaml
- [x] http/fuzzing/wordpress-themes-detect.yaml
- [ ] http/fuzzing/wordpress-weak-credentials.yaml
- [ ] http/miscellaneous/defacement-detect.yaml
- [ ] http/miscellaneous/ntlm-directories.yaml
- [ ] http/misconfiguration/aem/aem-default-get-servlet.yaml
- [ ] http/misconfiguration/aem/aem-gql-servlet.yaml
- [ ] http/misconfiguration/akamai/akamai-s3-cache-poisoning.yaml
- [ ] http/misconfiguration/default-spx-key.yaml
- [ ] http/misconfiguration/gitlab/gitlab-api-user-enum.yaml
- [ ] http/misconfiguration/gitlab/gitlab-user-enum.yaml
- [ ] http/misconfiguration/jolokia/jolokia-info-disclosure.yaml
- [ ] http/misconfiguration/phpmyadmin/phpmyadmin-setup.yaml
- [ ] http/misconfiguration/proxy/open-proxy-internal.yaml
- [ ] http/misconfiguration/servicenow-widget-misconfig.yaml
- [ ] http/technologies/graphql-detect.yaml
- [ ] http/technologies/graylog/graylog-api-exposure.yaml
- [ ] http/technologies/microstrategy-detect.yaml
- [ ] http/technologies/telerik/telerik-dialoghandler-detect.yaml
- [ ] http/vulnerabilities/apache/shiro/shiro-deserialization-detection.yaml
- [ ] http/vulnerabilities/generic/cors-misconfig.yaml
- [ ] http/vulnerabilities/generic/generic-env.yaml
- [x] http/vulnerabilities/generic/generic-j2ee-lfi.yaml
- [x] http/vulnerabilities/generic/generic-linux-lfi.yaml
- [x] http/vulnerabilities/generic/generic-windows-lfi.yaml
- [ ] http/vulnerabilities/generic/open-redirect-generic.yaml
- [ ] http/vulnerabilities/generic/xss-fuzz.yaml
- [ ] http/vulnerabilities/grafana/grafana-file-read.yaml
- [ ] http/vulnerabilities/other/bitrix-open-redirect.yaml
- [ ] http/vulnerabilities/tongda/tongda-auth-bypass.yaml
- [ ] http/vulnerabilities/wordpress/wordpress-accessible-wpconfig.yaml
- [ ] http/vulnerabilities/wordpress/wp-xmlrpc-brute-force.yaml
- [ ] javascript/audit/mysql/mysql-load-file.yaml
- [ ] javascript/default-logins/ssh-default-logins.yaml
- [ ] javascript/enumeration/mysql/mysql-default-login.yaml
- [ ] javascript/enumeration/mysql/mysql-show-databases.yaml
- [ ] javascript/enumeration/mysql/mysql-show-variables.yaml
- [ ] javascript/enumeration/mysql/mysql-user-enum.yaml
- [ ] javascript/enumeration/pgsql/pgsql-default-db.yaml
```

### Steps To Reproduce

See https://github.com/projectdiscovery/nuclei-templates/pull/11235 for example.

### Anything else?

This can help to reduce nuclei run time while running vulnerability scan with all default templates.
