### ISSUE TITLE
Create scan config profiles for different use cases

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#8839]
### Please describe your feature request:
Context: https://github.com/projectdiscovery/nuclei-templates/issues/8674

```[tasklist]
### Tasks
- [x] Recommended Templates (templates) https://github.com/projectdiscovery/nuclei-templates/pull/8829
- [ ] Fuzzing (DAST) (templates)
- [ ] Fuzzing (Bruteforce) (templates)
- [ ] OSINT (templates)
- [ ] Pentest (templates)
- [ ] Bugbounty (templates)
- [ ] Fingerprinting (templates)
- [ ] SAST (templates)
- [ ] Secrets (templates)
- [ ] Configs (templates)
- [ ] API Testing (templates)
- [ ] Host spray (scanning)
- [ ] Template spray (scanning)
```

### Describe the use case of this feature:
Preconfigured scan / template configs for different use cases.

**Comment by princechaddha** [comment]
Closing this issue due to inactivity. We already have added a lot of profiles for different use cases and will continue to improve that
